# Form implementation generated from reading ui file 'MainWindow_test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 717)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(850, 540, 210, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.TUM_Logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.TUM_Logo.setEnabled(True)
        self.TUM_Logo.setGeometry(QtCore.QRect(700, 30, 381, 131))
        self.TUM_Logo.setPixmap(QtGui.QPixmap("TUM_Logo_extern_mt_EN_RGB_p.png"))
        self.TUM_Logo.setScaledContents(True)
        self.TUM_Logo.setObjectName("TUM_Logo")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(41, 61, 212, 437))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.secondWindow = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.secondWindow.setObjectName("secondWindow")
        self.verticalLayout.addWidget(self.secondWindow)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.Boundaries = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.Boundaries.setObjectName("Boundaries")
        self.verticalLayout.addWidget(self.Boundaries)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "Help"))
        self.secondWindow.setText(_translate("MainWindow", "secondWindow"))
        self.pushButton_7.setText(_translate("MainWindow", "Delete Particles"))
        self.Boundaries.setText(_translate("MainWindow", "Create Boundaries"))
        self.pushButton_8.setText(_translate("MainWindow", "Delete Boundaries"))
        self.pushButton_4.setText(_translate("MainWindow", "Preview Assembly"))
        self.pushButton_6.setText(_translate("MainWindow", "System Properties"))
        self.pushButton_5.setText(_translate("MainWindow", "Run Simulation"))
